language: go
go:
- 1.10.x
before_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
after_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
stages:
- compile
- test
- name: acceptance
  if: branch = master OR type = pull_request
jobs:
  include:
  - stage: compile
    script: make
  - stage: test
    script: make unit
  - stage: acceptance
    script: make integration
notifications:
  slack: ignw:IxpMZ19gbbzU0vAM2SjvGtFx
env:
  global:
  - secure: zusKnT8Lye0r3WFFj4NHY+FGiXgujw/cQ6aB6dXEIKwazy5QLzZ2GjC2VKsEQC2IctvNyIy73EP7EwUQVUvAtGYMT/+5Fji2DbUoY67E98DXwRwp/DOO9hNOVx3eN+CvwFJXb4Asq1tJruvslPAfCCg5pA6LabCAwo47fWZSZ3NFiQiQL9naUgXWXHeW+OSeORjkz7fWUHE24Okrqeb5RrE4BVBMy55pqrv0ojLf9UjcMJMOyGqb6hdA3jzEW0LmjS4Nq0YDg71KG00/5Ls3178HGibgbSbnnw2Ov3si4lTbJtsctuPX3qxpjZ5zFHyb3bAJCcbHA9A/ilcOZ/Jp91JIY6z30I9OBlvv7cfz3CrJUCyNay2obpnxYeyEjKVp53ZWMqPRQ8orqUQgoE78lRq9qoi2viXuzM4xZa0PlluABZ6j088vOH4auFiAmyeKIY6mRomBu/3tip7Ese2+Jedbd6JryZraAMn9DvOKvjHMngh5xxUm1MgicKmjIvemgLssSrHFlpiN4+vQY1H6UVqt26vEjoGBmzctNVcd6Zp7NHDL67jIlrryuCsMuxWbkFNEpNYzDN1vRSgu1FxnikCH7sOhvkVGqqt/KUx6ERuTlp1Sh9X9+8e94nHFaeQyRJQb8AMY8ZhhFiCLtLl5vCSxKWdWxmKKLwlPL3b6V2I=
  - secure: r4wgdOLK5zkMN2/+NMZQN5XOICSPivwQ577ej3pKF6MEItl2qT60jB9mX/kgmuCiAcZWMFEFbZaDJV1t7xMtW3rIl1RBjcHQHVbNZDDBTKZRvittw37UlcpBcGy+Ok5oLyQDo3lihihla+cbJTuTPEBiCr4oJzPJHWsGSSMx1G5mtbMVHqBcCBATn6yppaC5vE99XlFEFMnlsyonD68Jh9LxDDm5/DE4zPv3kYVjM4NtuKqQ54IJICtbDrfzB21RyyfrIAM3OcVmFkfHn+A1WnmEb+B4EbVBSe2/rTdOxN8dxQrqLu2WVzJuzlcVtYOSux/QFCjwMGg2IZpdPU/h5Q3aJmYnzQ7mLCU8D3V603cPMe6bbdg+zKvo07nncbYP8FYF83HTJXj1dGiMDuug86+gs0hCVSIxJXOk+SYqovUY2r3BP/3GvFo3pfDjEftaAz6g9DPxbsNmgZtlcBZnhO014rA2HqyzdVoFUHjDmA71vBOT4Xi9bviWeg3fLHJRQw/ua4PpQrmHQS17+ulLNlImGZ+p/KSvVoBkLWb+erlWbBQDe8e23EWsb6vadcT8dl8Ubu6ZzJqAB9W7koxNmmG6pn6bBzN8pKSuNPD8Nk12pz5xZbn60KDiaZlO5IhH2CVt0eiG8bce5AwtZ5/pJ2/YmcnNJcGMN2yvwhaI2go=
  - secure: g/m/3hZjugQG+bbNtTGiHGxiemQEoQlPGnuVi5Is7FfDHPPm640B62BohGDfdmdNNjxtqFDkvh8RAT7RirJI4WsF/03IOVyWiHwryIbc4zUX4FtNGH36F8oFZiAVpX3zFllvYeEWtitf6Y94ZNpuI8jyNcqzoAyl1Q5EWJSgKP8WCsrhzGABZ3ZWwoX8B5pm1dB4GXpC0IxbjnBS1iUZEQ3sGwCURIslrhFHiFqYJXEMiqV5+I6FpF7G0jpEP5UuIZFObgh/2U4EYbikPBu+yZ5AwoLhdWxQooskxxJ5jRo3K9/HGJADMn2fxJ7icL+mJAdLZPe7B+ehBeumHZ7ejdcIzaKzwRUOCkftwnIGolbjA2bu4mWCJTcz4nhBesLwGHGU2co05Xf3qFyJLBogxcbP+IN45Iv6EibwGf7hLeF6g72yAIY3HA/xL9sTmJ0nSE3oHRpEQeufDybxbE57HtkC2nVIjkKLLvvuXQ/Hnjj37FXqZQaVsfjUJyMsjGzw7g62RsWIRxQK1+40B7IPdMqSMpdnyOKkAuC4TiZcBt0yswqrbTpvgwOylw942XqDz6DyIT9140pky+cDDlTDBp35JyZJixdJ7Se5BaTMjW49r71pR+obinwqB1SK6pbh6h2pkMIIvJGj1oSSUPWm8MYv0M0C6ydjSv4FQQvyfig=
  - secure: tWDvz0L7aeP8pjfhdREZ0VXB1w7oIiVcnIoAvjyNQMMDjwympUfBhAHoxC//1c2baW6+eS3rtxmdc1h3VY0uAJQ87lcqRFYSL0snvhnwBD8MG7uDTzZFP3+xPpBvFDFafeAU5extSE7sLGp/b8sYwunWVQ8M68hnbiVzgcd3bOWYFqzEi+pKoeEcikGacHYsFRzPgwEcCXl8hl0ezRd1Nj8QSpVX2l+C4fX9YXVKdw2ZFVaRE3nvkIQ7maiKp3ikumLIoVRNvej32Wu9LHBn+GQaEuQ8I/CZXiyUKGxXmzUEdBpdrbv2b0Skd9QoAvZLCXsOxCRQxmja4pTDmGSWjBRqKEk/5J4nC5cPrb8aT4Hs5lxlg2pv7dPjtCi069CgBPucHcglEDmXi+CpprW/q8r3Krc+uWmJuSBo3C8Jhm8hUlazXYtAODdiN9rZJwWmmStFnD7zRhlnjI9Gj28Z7qkuzTgUuoey1DWv1c+mgHMsFuiTtEuAqNZEJN3SLSnuw9mWjy9sAXKsoCf1DrezE6ibNnleb8LJ0Bpcjt0eLXraRcEw33t/RPb86RA29CUpEH72Bo56XB27tJSe7KhKrAZ/lyuCJ/j6oFRHVQazW34vAI6t1dPIAJ9NNKWvFRzj37DiaoN60ziY2/JJBwJC831tSspf7T03HHCxK7jjmII=
