language: go
go:
- 1.10.x
before_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
after_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
stages:
- compile
- test
- name: acceptance
  if: branch = master OR type = pull_request
jobs:
  include:
  - stage: compile
    script: make
  - stage: test
    script: make unit
  - stage: acceptance
    script: make integration
notifications:
  slack: ignw:IxpMZ19gbbzU0vAM2SjvGtFx
env:
  global:
  - secure: ShjFwGVQWK2VjruyO1sZo6rPDv/K7WkSTVvpPb0ReGPSp6nqBvH/ta1bMMxBt2Yllfn6rXBVePRwePWwa1cYFDmjofU2jX9NG7H610lCwLSmT5Kr838AkROE7q8kuRXCBtT3qb5pF80/AXTULPZss067aIgqgmiUGKNgSUpywmT1R6cW/1u/UJP+9T/A/HEZh94AocBrCUCkQdflz/o29GNIGlaKJPVY93ZTSwS9dESKktIkFScmVPrTR5rXQ8s4dSx69Sgp7a8pKIwL3+Xv0+OfW0t3f7DVkkUh4NbI0u5ZqBD4cPzCTUmWLZYQ4wcEZs0k1LZwFqavPLSVrqfzinc5fJ0n463MbSJEp1mn1711d+r88vIrgNvxjBY7IVX5APL1fxo1vgHak+wOWw1p2MGSfKpejHc2PU3ojSv6g7yrAPLy3S6mNxPoCfFB7VYz92RJGwcUUBI5fs9j71yuz9HIERO3bvmRIfhn7RI4gZpqdKpPmYVd1iNY49neqXpxSn42v+8VRdkHbWhWqle5H2nUNS6JP5BlIrWbPoY8d9VTNqPwLco3PrZaSUw1w20l7RiGPqe/I4l1I9H4Lg5UwG4M+91rOVCH9jnpS55CR44CogCvZapCvZzI0cU0CTMHjOqMDJm0chYosAPlf7zNCB2axghBHfy2OyFLrNPek30=
  - secure: em7B7JBXAmKYufV+b6Z7UQpBX1R9BBZCfG/STT9mHqQm1zdPTU7Hnwc7600FmyFX/TfwJ5I2JzO09xsIWSTvwLsRLOz4c+gnaoV/TZpMLVq7k80aiRnOWOpj9jgIKsLwgJD6H1J7Ti1E600RGe7u+PTrYNBr1+6A4sARPuU36RfYWSz9cg3Qeu1DZrg1sFwQiCGu+el2ms4vVdIU0Ay3Q8T6IiwulwiHEfC/XP9jyx77VBe6UHiyQ5w0cItLx9WEGvKBKEo59eMd2gI5XBTbhs2jWLaicu+UisWJHv4fsBhFmsTuS+jNglDLPipJtE7gq4NM3JDcEmTMe1B9kBOTA9OPYRxxOTDrsFNxmrTo0zd++OaKKMFxuRcZev0WLAuOcYd5ISfO71IWCC54lCG0vt+H+ptnrBla4oVHr6TmqoWdW6fTm01ZvtXyXZzslunT9IJnyHW0m0BLH5+VZNxctP5Ay5qIexbxTDMv1HVV5kplapqQ36xt4gCHaFzBQSJTzm30CeqGCvQpqEcg7UYYomnPpy5gnpLPNqrVBjGbeMEJ/fr9Lzlam8samHfeyRNbxLZXNW4Nz1Sp1pRT98mJ28jTb0beTq8vbMwyYddeLDx/yPOsCOdjhL+jNc+dHx8mc5HLEDQ1gwnrdoka/BVZSTsNRmAzxMvNFm2QJhthLbM=
  - secure: VCdxH7kjaiRPBV9ALIynoM1H8E2YGdG0c3EZjZc4SLeKQkZzror+8XnFYvFOyxo6w8+VYUQAwglRrgN7bCVdGvQdLtwfOJK3WnznT3Njg//Q+ijkzNHt1xBaYqgfiKbAIKl9x4Q7/6nnpMIyPvH5JiHv74ZzLVJDWi+dAFmnmbKTZpbscnrkyc2TLM7spDgYvHyKH7WbmKiKrWgPSaogP87vvnvtymhmoXXBLEFJ0ZHqkCUFELEdNX0fmk7sMHT87ZkO+EBcWmca8q2J9QBA+dg1eSc5J6N/8xysgwr02H41uTu5UBDiUaa4RTAe5IrRqM7evgILGbNZhiDbtM4/PQnlOrnZ0zrf6XI4V2uhtWhn2h8JaSBRtngtk26rMZj+zhkSbC0snwtftMFjwzxzn+tcROF2dl0kdw2p0A1Vf6WbYhCC/NX0YsssGgy/uQYmXoAF1vIAL8/gGJZjIOwn5ukTcGNtRiBFYBxkMq4sA8avwKmN+HoNcL2CnbcB/DWrJrYcTyXjBnI0VtmNAZtevVEKNJsiLz2xWveIFA+cWXGtIZvghxSUnS1TIxRwrFWSlFDpnTemDLOiY/SlDVDfrkGPbw+BOegqi279qufjmZqaOIBH/tiqHsrL7rtmRoB0A08CmLDMq1mdvvy10lB5qdChfhU7ekwgCWYRw4l5xkQ=
  - secure: Me6Mz1OihQl7nQRFL2C4aDaU2aAWGSFlpfuj25u5R0QuoKC2vbSPXc0jt5v3jkd9csGPwyeefG6JRStYZztaiZEistsLCfcI25dB5k9Tunkj3pqv8/PJ0sm14QE0nka3X1EPyJUStOAzlAQdGePFYPgPKaANLKjkXmE8zqD7eVSfJmN961gH3XDNsESOnGJtpqeUXQ9WXIa0XKEX/ZCVWXax/XUmG/Zd3//Go2tuRwQfyTXakGSMg0WYMeuFRBVqxYx69jF99z+kVxYanw+pac60dVUO5wD8hL1q1wt1PV0SVTStUChCgQrO2WLS2YymSUqJbKCdB81TMXn4KjEO4myE80SqXLLO9LDFt+PMxopX0sWfnus+ay/KbFYhGYMK/J/GkZXyvFb0emVanb6j3YgfbonTsHeQ+ulbEdt5wLdT38BvwlY5ZYMf1nysCqnJJr2IXwpXovfeUc1tUHxJtB/NvpufX5QwMLxocRyInchEWaG3USyi6HEzaCLXcIYdk70tXK4Iv5Df4ZcJ7PjN1FY1/9udg5KHfn52upW3R8hIipe1tjuLTBbTAbi7yGEDmbjJlzDGk65qcEh92O+wBwbmN0EtlvC9A5S72L62hJBe1GL6zX+Tu1IBShkD0hRW70RJOCMxzcKrAOY0/fCEL/r83vStBFEI6VWdME3WEnY=
