language: go
go:
- 1.10.x
before_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
after_install:
- find $GOPATH/src/github.com/ -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {}
  \;
stages:
- compile
- test
- name: acceptance
  if: branch = master OR type = pull_request
jobs:
  include:
  - stage: compile
    script: make
  - stage: test
    script: make unit
  - stage: acceptance
    script: make integration
notifications:
  slack: ignw:IxpMZ19gbbzU0vAM2SjvGtFx
env:
  global:
  - secure: CJ/L7SnPsyaTTk7QOL/Q0XEMkC1S/DrnXge0DsTbrfLsjPxktGE6W2Odznqr3iamcbhvPbO6Z6NoKPHSNdGaZBOcFMc/KRDDOOrYI5O/F9U7JB8RV0LFg7zcncx8hOY141vxwu0c/fCsWu6l+9QuAqiwsMq7Uh30vqO1J/j4XBJE87zWH5OAFo/k22YqnQhg7SIX12Ovjel15HWZyVpyx2QY0+xcvSVz8MR1ohYWhPNjUHrEvdkSn8aL5ArIiohHbYmh8Fhfsoc6HS7JbwfNINlZqepvYrvPeFfFOGj/5C/XSr3Kg3hZ2AFEOmklDWKzg56kfCuNUINx9QgLC/LAO1+yBxi90M5m+t4LS7IiZIgqqFeiObwBVXzXv3a73KwqRbgYjGEyTMdov8znwVqst1EGcH11F5k2xDpiJSfrEGBHJaVVW674z3lG1F/QFJTia45u0oyFpgiuFHPDTXmlpT7npsn0I+hHwwWF3Vmu1hz+aIPUqRln9Nc8q2ezj0lIzX3BJYW40zq5JOg7RalApbpK85PYJdci5ROAjDe9PgvXxG3yggco63wdU+QuGKmXS0TYjPXOS3FxkN7H74neTZh1VJHlH4CZp4NlyzqWpFhAFBx1UGQcXLpp1VZcarfbw4tSnkZcZfQZWowXikCu+k4jcCuLfSmB5kqlHfM/X+c=
  - secure: kny2gj1ccnjjv6XruCFz53nYXPsBa+ieHGZSVSA1t+k5PpDpSSVRgWe30p+dqcaWCasS/QPWza/wd1r5HSqAyDRzPFVPd6EZ1aQgQRLGpF4zrmrBSgmTlc8BoT6hBWFVovnzwtjs8MDrM+z3g+SgdJ6SGzN7Pc/gaDTO3Kx5+mHiPSHf5bV8Sol7OTI74ZCcZ1xzksVjHAyMYsq3QWDWgkw61fE57XvbQIkgS396V0p/jGhNoT6h17IxVonuvic3flhz1ITnoBjPSm7tOmc3nsr267Wao1CfWLKxqNbLbVe2YdQVvKB/gRtbfgt8C6hgGRUumlznKo+9834h4bGaiQWFcjg+ZIVatH8dpnP+PEe4tMTAPtA4lnrLa39h4FTTh6YLUMqSIwFokCz4li8qOUGfMQEikC6vG3T8XnoXxGBZEbiHQhCRz4jdxOaJD98fY4rkfUuBlS/xY524hH1bWNneqJXf+Oii/aabJdwUdFtggTz+AxlKAdq/veenhyZPBzY4bOnFNSTe/auT6r1ojVffP8PcIz35Jc/T6OTunilfo8vYMVRSxOiqX26IFCw9dUh/kbbzu+gpii3rH7RCfkVz0CzYzq3Aw85peFYI8gQgf8b60Q6Nlxnyy59cVEtpCTzHwjkZ9RzL11VSbekI9fcDs3T/kSt+XL1Rm4vI8Gs=
  - secure: aO5C9aFn83ZUV7fjdOYNtPK3GDluZ6HMTbw4e3BVCEXnZEnRGklJ7bpAuCzTIIhjVCPtQNXhStdySzCrkBO+GFRPNSILVmq+okdKq9i8AEZevtqYbRxmVEqAAoWgVJ63ArHM4PoSJmYC0Q3ymtGIpfFxNPsfL1CRkIITGRkc2Cj720PdSjcXN3nYfFVqKWj1w9EzSy22vdiYCGM1ZLOJMLfTr8mJgfAMAJnxU/JJKB2nTnzU+SI40+bUVo3aM8X6PI662dX/PXHZGZgOrHA9/+hgODCtTjqrWnPH1YKBGRynos29X4+Rp/q989eferdGjpX8CGYuI6FxvSADwtB/hpYDh62cct4Nz5VDv+zSSB2kSHA3OjSPOFyKDDjGk7uTHkYGyL2+zvY+zlU1pfZgkiwYMXDffBA2vASMwUMcCcTI8fXhR1PaRDiCiHQaDtsq6Lp/ql7+/t437lYhRvZ4W7M/hzEzSrOgIjRLkAPHEwwmsDtyTi62qQk33kmLmiwmd6MqOUWzeSslu7mMh+MHnynQVCseG0qfdljTYzKp2DZKjBBeW4ucv57znzIPm9Gc9QdRLn+Yqsvm+fivzVA6STKkDZcbYxViJWKSWLe0DaD9sFCu3j8n1iQ5LW18GjgyjFe4JOiI40Y2INUu06esgSOt7mcZW5HQfgrJhOJ9N+U=
  - secure: EPGydWuHeayQ2vSfvXiZomcvbTsSYLsmks0DDCDlZyTA5U+Ym7UV1gbcwKNbeO11Jx8ngd4UdC9JXAYXLQ5JFXpoS8TG6y5iTejUj9bIM7+IAb58DYy3JPOd6EMezEU5C3RYgwANNWsZ2XVJZg+9BX6wbD54/boOvF6Og9QbLmjNnK2AsIqzX5IVeEnEaGx5pgU+4CJcfSfaqMWiYgCf3p+qrrRCyIfjEqDnMNCkOH7vcn/+4fWumoLMaVOb06Za3Fdf34FPAaPPdUXdAGLNje4DyOcq0d9Q/4js76H+QhTxYAXq5V2ZmY6m0ZHHxijslFJdjYsYOo1sV5OxdndofpClQS8Liq9YoHKvsnqdeDAyW9A7Dmxv4SQwslGhFOBH6dcdlomPSzimNJya+/TfY2XDUejKRRloRi+lElbi0QYQEAF8JT1e/GaxGkgCuPmlMJvuaLiOJVtYcBaVXgQB7ZLeS0d7lDF3YjvP03mmQudoGiSL/0Nuec9RMTfQWPivsgSKuwWBVdIrH4IYLAEIbTArNag5wPxIDdewTRWjD6K2pin6UT2Qn6iW6yda5hykpsUjLNLsGGIbJK+YuSyZX5K/jbVSWLz19SzP6LZrN/YplJFafJsgtuGIuVNLtmI94TZUaqqna5PbqyC1nLF9Biq+Ff2CQrC/TiEn+YXK9kM=
